name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install GoReleaser
        run: |
          curl -sL https://git.io/goreleaser | bash

      - name: Run GoReleaser
        run: goreleaser release --rm-dist

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_darryl443 }}
          password: ${{ secrets.DOCKERHUB_docker login -u darryl443 }}

      - name: Build and push Docker image
        run: |
          TAG=$(git describe --tags)
          docker build -t ${{ secrets.DOCKERHUB_darryl44 }}/${{ secrets.GITHUB_REPOSITORY }}:$TAG .
          docker push ${{ secrets.DOCKERHUB_darryl44 }}/${{ secrets.GITHUB_REPOSITORY }}:$TAG
